/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bjxllzwefbewjrrwhhjt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqeGxsendlZmJld2pycndoaGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0NjE0OTIsImV4cCI6MjEwMjAzNzQ5Mn0.Y88ExVcbOozDYZeQiYI3okkZ-_mSHmsK6e-gBOWrzH0"